version: 0.2

phases:
  pre_build:
    commands:
      - docker login -u AWS -p $(aws ecr get-login-password --region $AWS_DEFAULT_REGION) $AWS_ACCOUNT_ID.dkr.ecr.eu-central-1.amazonaws.com
      #- docker build -t builddown -t $AWS_ACCOUNT_ID.dkr.ecr.eu-central-1.amazonaws.com/builddown:latest .
      #- docker push $AWS_ACCOUNT_ID.dkr.ecr.eu-central-1.amazonaws.com/builddown:latest
  build:
    commands:
      - echo Build started on `date`
      - echo "artifact research" > test.txt
      - echo $(pwd) >> test.txt
      - echo $(ls -hal) >> test.txt
      - echo Pulling the Docker image...
      - docker pull $AWS_ACCOUNT_ID.dkr.ecr.eu-central-1.amazonaws.com/builddown:latest
      - docker run -v $(pwd):/data 535413804026.dkr.ecr.eu-central-1.amazonaws.com/builddown /bin/sh -c 'cd /data; Rscript make_drake.R'
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - data/article.html
    - test.txt