version: 0.2

phases:
  pre_build:
    commands:
      - docker build -t builddown .
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker run builddown /bin/sh Rscript make_drake.R
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - article.html