  
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/github.com/radbrt/builddown:$SHORT_SHA', '-t', 'gcr.io/$PROJECT_ID/github.com/radbrt/builddown:latest', '.' ]
  timeout: 3600s
- name: 'gcr.io/$PROJECT_ID/github.com/radbrt/builddown:$SHORT_SHA'
  args: ['Rscript', 'make_drake.R']

artifacts:
  objects:
    location: 'gs://com_radbrt_builddown/'
    paths: ['new_sources_$SHORT_SHA.pdf']


images:
  - 'gcr.io/$PROJECT_ID/github.com/radbrt/builddown:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/github.com/radbrt/builddown:latest'

options:
  machineType: 'N1_HIGHCPU_8'

timeout: 3600s

tags:
  - "buildarticle"
